run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - misspell
    - unconvert
    - unparam

linters-settings:
  goimports:
    local-prefixes: github.com/murasame29/unifi-client-go

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
